config:
  slack:
    botToken: topSecret!
    botID: supernova
    accessToken: topSecret!
    verificationToken: topSecret!
    authorizedUserGroupNames:
      - groupA
      - groupB

  pagerduty:
    defaultEmail: a@b.de
    authToken: topSecret!