replicaCount: 1

isDebug: false

image:
  repository: sapcc/pulsar
  tag: v1.0.1
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 8080

ingress:
  annotations:
    vice-president: "true"
    ingress.kubernetes.io/ingress.class: nginx-internet
    kubernetes.io/ingress.class: nginx-internet

  hosts: []

config:
  slack:
    # botToken:
    # botID:
    # accessToken:
    # verificationToken:
    authorizedUserGroupNames: []

  pagerduty: {}
    # defaultEmail:
    # authToken:
