apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: {{ include "pulsar.fullname" . }}-secret
  labels:
    {{- include "pulsar.labels" . | nindent 4 }}

data:
  slack-bot-token: {{ required ".Values.config.slack.botToken missing" .Values.config.slack.botToken | b64enc | quote }}
  slack-bot-id: {{ required ".Values.config.slack.botID missing" .Values.config.slack.botID | b64enc | quote }}
  slack-access-token: {{ required ".Values.slack.accessToken missing" .Values.config.slack.accessToken | b64enc | quote }}
  slack-verification-token: {{ required ".Values.config.slack.verificationToken missing" .Values.config.slack.verificationToken | b64enc | quote }}
  slack-authorized-user-group-names: {{ required ".Values.config.slack.authorizedUserGroupNames missing" ((join "," .Values.config.slack.authorizedUserGroupNames)) | b64enc | quote }}
  pagerduty-default-email: {{ required ".Values.config.pagerduty.defaultEmail missing" .Values.config.pagerduty.defaultEmail | b64enc | quote }}
  pagerduty-auth-token: {{ required ".Values.config.pagerduty.authToken missing" .Values.config.pagerduty.authToken | b64enc | quote }}
